#############################################################################
# Generated by PAGE version 4.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 15 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font15
vTcl:font:add_font \
    "-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.lab40
    set site_3_0 $base.lab51
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m46" -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 600x573+653+26
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1604 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Click Clicker"
    vTcl:DefineAlias "$top" "GameWindow" vTcl:Toplevel:WidgetProc "" 1
    labelframe $top.lab40 \
        -foreground black -relief raised -text Clicks -background {#d9d9d9} \
        -height 65 -width 150 
    vTcl:DefineAlias "$top.lab40" "CurrencyPanel" vTcl:WidgetProc "GameWindow" 1
    set site_3_0 $top.lab40
    label $site_3_0.lab56 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -relief flat -text {#ofclickshere} 
    vTcl:DefineAlias "$site_3_0.lab56" "ClicksAmntLabel" vTcl:WidgetProc "GameWindow" 1
    place $site_3_0.lab56 \
        -in $site_3_0 -x 10 -y 20 -width 124 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab42 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -relief sunken -text {Click Clicker} 
    vTcl:DefineAlias "$top.lab42" "title" vTcl:WidgetProc "GameWindow" 1
    labelframe $top.lab44 \
        -foreground black -text Clickers -background {#d9d9d9} -height 485 \
        -width 290 
    vTcl:DefineAlias "$top.lab44" "ClickersPanel" vTcl:WidgetProc "GameWindow" 1
    menu $top.m46 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    button $top.but47 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Click! 
    vTcl:DefineAlias "$top.but47" "ClickB" vTcl:WidgetProc "GameWindow" 1
    button $top.but48 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command {} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font15,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -overrelief groove -pady 0 -text {Throw Mouse Out A Window} 
    vTcl:DefineAlias "$top.but48" "TMOAWb" vTcl:WidgetProc "GameWindow" 1
    labelframe $top.lab51 \
        -foreground black -relief sunken -text {Save File Stuffs} \
        -background {#d9d9d9} -height 195 -width 280 
    vTcl:DefineAlias "$top.lab51" "Labelframe3" vTcl:WidgetProc "GameWindow" 1
    set site_3_0 $top.lab51
    button $site_3_0.but52 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Save Game} 
    vTcl:DefineAlias "$site_3_0.but52" "SaveSaveB" vTcl:WidgetProc "GameWindow" 1
    button $site_3_0.but53 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -state disabled \
        -text {Import Save (CS)} 
    vTcl:DefineAlias "$site_3_0.but53" "SaveImportB" vTcl:WidgetProc "GameWindow" 1
    button $site_3_0.but54 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Wipe Save} 
    vTcl:DefineAlias "$site_3_0.but54" "SaveWipeB" vTcl:WidgetProc "GameWindow" 1
    button $site_3_0.but55 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -state disabled \
        -text {Export Save (CS)} 
    vTcl:DefineAlias "$site_3_0.but55" "SaveExportB" vTcl:WidgetProc "GameWindow" 1
    place $site_3_0.but52 \
        -in $site_3_0 -x 10 -y 20 -width 127 -relwidth 0 -height 74 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but53 \
        -in $site_3_0 -x 10 -y 110 -width 127 -relwidth 0 -height 74 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 150 -y 20 -width 117 -relwidth 0 -height 74 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but55 \
        -in $site_3_0 -x 150 -y 110 -width 117 -relwidth 0 -height 74 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab40 \
        -in $top -x 440 -y 10 -width 150 -relwidth 0 -height 65 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab42 \
        -in $top -x 10 -y 10 -width 421 -relwidth 0 -height 61 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 300 -y 80 -width 290 -relwidth 0 -height 485 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 10 -y 90 -width 277 -relwidth 0 -height 124 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 10 -y 230 -width 277 -relwidth 0 -height 134 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 10 -y 370 -width 280 -relwidth 0 -height 195 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

